iqiyi_avon_preparepage:
    pattern:  /
    defaults: { _controller: IqiyiAvonBundle:Home:prepare }

iqiyi_avon_homepage:
    pattern:  /home
    defaults: { _controller: IqiyiAvonBundle:Home:index }

iqiyi_avon_addphoto:
    pattern:  /addphoto
    defaults: { _controller: IqiyiAvonBundle:Home:addphoto }

iqiyi_avon_addmsg:
    pattern:  /addmsg
    defaults: { _controller: IqiyiAvonBundle:Home:addmsg }

iqiyi_avon_votemsg:
    pattern:  /votemsg/{id}
    defaults: { _controller: IqiyiAvonBundle:Home:votemsg }
    requirements:
        page:  \d+

##############################################################

login:
    path:  /admin/login
    defaults: { _controller: IqiyiAvonBundle:Backend:login }

login_check:
    path:  /login_check

logout:
    path:   /logout

iqiyi_avon_redeem_backend:
    pattern:  /admin/redeem
    defaults: { _controller: IqiyiAvonBundle:Backend:redeem }

iqiyi_avon_generate_redeem:
    pattern:  /admin/redeem/generate
    defaults: { _controller: IqiyiAvonBundle:Backend:generateRedeemCode }
    
iqiyi_avon_download_redeem:
    pattern:  /admin/redeem/download
    defaults: { _controller: IqiyiAvonBundle:Backend:downloadRedeem }

#backend subject
iqiyi_avon_subject_list:
    pattern:  /admin/subject/list/{page}
    defaults: { _controller: IqiyiAvonBundle:Backend:subjectList, page: 1 }
    requirements:
        page:  \d+

iqiyi_avon_subject_approve:
    pattern:  /admin/subject/{id}/approve/{status}
    defaults: { _controller: IqiyiAvonBundle:Backend:subjectApprove}
    requirements:
        id:  \d+
        statis: 0|1

iqiyi_avon_subject_remove:
    pattern:  /admin/subject/{id}/remove
    defaults: { _controller: IqiyiAvonBundle:Backend:subjectRemove}
    requirements:
        id:  \d+

iqiyi_avon_subject_update_vote:
    pattern:  /admin/subject/{id}/vote
    defaults: { _controller: IqiyiAvonBundle:Backend:subjectVote}
    requirements:
        id:  \d+

iqiyi_avon_subject_vote_list:
    pattern:  /admin/subject/vote/list/{page}
    defaults: { _controller: IqiyiAvonBundle:Backend:subjectVoteList, page: 1 }
    requirements:
        page:  \d+

#backend photo
iqiyi_avon_photo_list:
    pattern:  /admin/photo/list/{page}
    defaults: { _controller: IqiyiAvonBundle:Backend:photoList, page: 1 }
    requirements:
        page:  \d+

iqiyi_avon_photo_approve:
    pattern:  /admin/photo/{id}/approve/{status}
    defaults: { _controller: IqiyiAvonBundle:Backend:photoApprove}
    requirements:
        id:  \d+
        statis: 0|1

iqiyi_avon_photo_remove:
    pattern:  /admin/photo/{id}/remove
    defaults: { _controller: IqiyiAvonBundle:Backend:photoRemove}
    requirements:
        id:  \d+

iqiyi_avon_photo_update_vote:
    pattern:  /admin/photo/{id}/vote
    defaults: { _controller: IqiyiAvonBundle:Backend:photoVote}
    requirements:
        id:  \d+

iqiyi_avon_photo_vote_list:
    pattern:  /admin/photo/vote/list/{page}
    defaults: { _controller: IqiyiAvonBundle:Backend:photoVoteList, page: 1 }
    requirements:
        page:  \d+
